from .base_discriminator import BaseDiscriminator
from .base_critic import BaseCritic
from .dcgan_discriminator import DcganDiscriminator
from .esrgan_discriminator import EsrganDiscriminator
from .linear_discriminator import LinearDiscriminator
from .patchgan_discriminator import PatchganDiscriminator
