from .spade import SpadeSisrGenerator
from .progressive_spade import ProgressiveSpadeGenerator
from .dcgan_generator import DcganGenerator
from .linear_generator import LinearGenerator
from .progressive_esrgan import EsrganProgressiveGenerator
from .progressive_rcan import ResidualChannelAttentionGenerator
from .simple_esrgan import SimpleEsrganGenerator
from .alternative_esrgan import AlternativeEsrganGenerator
from .unet import UNet
